const formContainer = document.querySelector('#form_container')
const fname = document.querySelector('#fname')
const lname = document.querySelector('#lname')
const email = document.querySelector('#email')
const radio1 = document.querySelector('#radio1')
const radio2 = document.querySelector('#radio2')
const msg = document.querySelector('#msg')
const checkBox = document.querySelector('#checkbox')
const submitBtn = document.getElementById('submit-btn')

const error1 = document.getElementById('error1')
const error2 = document.getElementById('error2')
const error3 = document.getElementById('error3')
const error4 = document.getElementById('error4')
const error5 = document.getElementById('error5')
const error6 = document.getElementById('error6')